#!/usr/bin/env python3
"""Convert transparent dancer PNGs to deterministic LVGL RGB565A8 assets."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

from PIL import Image


SIZE = 112
CONTENT_SIZE = 104
NAMES = ("hiphop", "breaking", "funk", "locking")


def _fit_character(path: Path) -> Image.Image:
    image = Image.open(path).convert("RGBA")
    alpha = image.getchannel("A")
    bbox = alpha.getbbox()
    if bbox is None:
        raise ValueError(f"{path} contains no visible pixels")

    character = image.crop(bbox)
    character.thumbnail((CONTENT_SIZE, CONTENT_SIZE), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    x = (SIZE - character.width) // 2
    y = (SIZE - character.height) // 2
    canvas.alpha_composite(character, (x, y))
    return canvas


def _rgb565a8(image: Image.Image) -> bytes:
    colors = bytearray()
    alphas = bytearray()
    for red, green, blue, alpha in image.getdata():
        if alpha < 8:
            red = green = blue = alpha = 0
        value = ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)
        colors.extend((value & 0xFF, value >> 8))
        alphas.append(alpha)
    return bytes(colors + alphas)


def _format_bytes(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), 16):
        chunk = data[offset : offset + 16]
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def _header() -> str:
    declarations = "\n".join(
        f"extern const lv_image_dsc_t flow_dancer_{name};" for name in NAMES
    )
    return (
        "#pragma once\n\n"
        "#include \"lvgl.h\"\n\n"
        f"{declarations}\n"
    )


def _descriptor(name: str, data: bytes) -> str:
    symbol = f"flow_dancer_{name}"
    return f"""static const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST
uint8_t {symbol}_map[] = {{
{_format_bytes(data)}
}};

const lv_image_dsc_t {symbol} = {{
    .header = {{
        .magic = LV_IMAGE_HEADER_MAGIC,
        .cf = LV_COLOR_FORMAT_RGB565A8,
        .flags = 0,
        .w = {SIZE},
        .h = {SIZE},
        .stride = {SIZE * 2},
        .reserved_2 = 0,
    }},
    .data_size = {len(data)},
    .data = {symbol}_map,
    .reserved = NULL,
}};
"""


def convert(source: Path, output: Path) -> None:
    output.mkdir(parents=True, exist_ok=True)
    sections: Iterable[str] = (
        _descriptor(name, _rgb565a8(_fit_character(source / f"dancer_{name}.png")))
        for name in NAMES
    )
    c_text = (
        "/* Generated by tools/convert_dancer_art.py; do not edit. */\n"
        "#include \"flow_dancer_assets.h\"\n\n"
        "#ifndef LV_ATTRIBUTE_LARGE_CONST\n"
        "#define LV_ATTRIBUTE_LARGE_CONST\n"
        "#endif\n\n"
        + "\n".join(sections)
    )
    (output / "flow_dancer_assets.h").write_text(_header())
    (output / "flow_dancer_assets.c").write_text(c_text)


def main() -> None:
    project = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=project / "assets" / "source")
    parser.add_argument(
        "--output",
        type=Path,
        default=project / "components" / "flow_ui" / "assets",
    )
    args = parser.parse_args()
    convert(args.source, args.output)


if __name__ == "__main__":
    main()
